### ISSUE TITLE
multi-head setup

### ISSUE THREAD

**Issue by moolen** [moolen/glitchlock#1]
issue: When using multiple displays only one of the displays - the primary - will be overlayed.

**Comment by mibcadet** [comment]
same here, really nice screen locking app but working only on one monitor blocks me from using it now

**Comment by moolen** [comment]
@mibcadet thank you for you feedback. I released a [alpha version](https://github.com/moolen/glitchlock/releases/tag/0.3-alpha) that implements a multi-monitor mode. However using `-censor` is problematic because it takes quite some time to find the words in both images.

Would you be so kind and test it with your setup <3?

**Comment by mibcadet** [comment]
Hi, thanks for really quick replay, I had day off so my answer is late :P Do I have to add any flag to use multi-head?

edit: I've checked your file 'main.go', I do not see any multi-head flag in it defined so I assume it should work out of the box. But it doesn't, still it is activated only on main screen. However all 3 screens (one laptop, 2 external) are locked, but graphics are displayed only on main screen.

**Comment by moolen** [comment]
yes, you don't need to specify a flag for that. I've created a [new release](https://github.com/moolen/glitchlock/releases/tag/0.3-alpha-2) that outputs debugging information for the connected displays.

Could you please run it in debug mode to see whether all screens are recognized or not:

```
$ glitchlock -version
glitchlock 0.3-alpha-2

$ glitchlock -debug
DEBU[0000] found 2 screens                              
DEBU[0000] screen 0 has bounds image.Rectangle{Min:image.Point{X:0, Y:0}, Max:image.Point{X:1920, Y:1080}} 
DEBU[0000] screen 1 has bounds image.Rectangle{Min:image.Point{X:0, Y:1080}, Max:image.Point{X:1920, Y:2160}} 
DEBU[0000] creating window using screen rect image.Rectangle{Min:image.Point{X:0, Y:0}, Max:image.Point{X:1920, Y:1080}}
DEBU[0000] creating window using screen rect image.Rectangle{Min:image.Point{X:0, Y:1080}, Max:image.Point{X:1920, Y:2160}} 
[...]

```
 and if not please post your `xrandr -q` output aswell as your window manager and/or distro you're using. Things might get hairy then to reproduce the issue :fearful:

**Comment by mibcadet** [comment]
Sure thing, here is glitchlock debug:

```
╭─smolka@mDev ~/Tools  
╰─$ chmod +x glitchlock-linux-x86_64                                                                                                                                                 126 ↵
╭─smolka@mDev ~/Tools  
╰─$ ./glitchlock-linux-x86_64 --version
glitchlog 0.3-alpha
╭─smolka@mDev ~/Tools  
╰─$ ./glitchlock-linux-x86_64 --debug  
DEBU[0000] found 3 screens                              
DEBU[0000] screen 0 has bounds image.Rectangle{Min:image.Point{X:0, Y:0}, Max:image.Point{X:1920, Y:1080}} 
DEBU[0000] screen 1 has bounds image.Rectangle{Min:image.Point{X:-3840, Y:-384}, Max:image.Point{X:-1920, Y:816}} 
DEBU[0000] screen 2 has bounds image.Rectangle{Min:image.Point{X:-1920, Y:-384}, Max:image.Point{X:0, Y:816}} 
DEBU[0001] creating window using screen rect image.Rectangle{Min:image.Point{X:0, Y:0}, Max:image.Point{X:1920, Y:1080}} 
DEBU[0001] creating window using screen rect image.Rectangle{Min:image.Point{X:-3840, Y:-384}, Max:image.Point{X:-1920, Y:816}} 
DEBU[0001] creating window using screen rect image.Rectangle{Min:image.Point{X:-1920, Y:-384}, Max:image.Point{X:0, Y:816}} 
DEBU[0004] timeout reached. clearing password     
```

xrandr -q (only connected)
```
╭─smolka@mDev ~/Tools  
╰─$ xrandr -q |grep " connected" -A1
eDP1 connected primary 1920x1080+3840+384 (normal left inverted right x axis y axis) 310mm x 170mm
   1920x1080     60.01*+  59.93  
--
DP1 connected 1920x1200+0+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95*+
--
DP2-2 connected 1920x1200+1920+0 (normal left inverted right x axis y axis) 520mm x 320mm
   1920x1200     59.95*+
```
my OS info:

> 
>                     /-                      smolka@mDev 
>                    ooo:                     ----------- 
>                   yoooo/                    OS: ArcoLinuxB-bspwm v6.9.2 
>                  yooooooo                   Kernel: 4.18.6-arch1-1-ARCH 
>                 yooooooooo                  Uptime: 3 hours, 32 mins 
>                yooooooooooo                 Packages: 1144 (pacman) 
>              .yooooooooooooo                Shell: zsh 5.5.1 
>             .oooooooooooooooo               Resolution: 1920x1080, 1920x1200, 1920x1200 
>            .oooooooarcoooooooo              WM: bspwm 
>           .ooooooooo-oooooooooo             Theme: Arc-Numix-Dark [GTK2/3] 
>          .ooooooooo-  oooooooooo            Icons: Sardi-Arc [GTK2/3] 
>         :ooooooooo.    :ooooooooo           Terminal: termite 
>        :ooooooooo.      :ooooooooo          Terminal Font: Monospace 12 
>       :oooarcooo         .oooarcooo         CPU: Intel i5-7300U (4) @ 3.500GHz 
>      :ooooooooy           .ooooooooo        GPU: Intel HD Graphics 620 
>     :ooooooooo   /ooooooooooooooooooo       Memory: 3033MiB / 15791MiB

**Comment by moolen** [comment]
@mibcadet thanks! I think i fixed it. Seems like bspwm adjusts the position of the window where he shouldn't. Can you please verify that it's working on your setup? <3

**Comment by mibcadet** [comment]
@moolen Sure, I will update you tomorrow, as then I will be connected to 2 additional screens.

Edit:
@moolen I've checked it, still same result, it displays on one screen and repositioned a bit from bottom (like 80-100 pixels).

I've used: https://github.com/moolen/glitchlock/releases/download/0.3-alpha-3/glitchlock-linux-x86_64

Did you seen it working on multi-headed bspwm or I am only tester? I ask because I am curious in case if only I have this issue.

![img_0838](https://user-images.githubusercontent.com/925500/45865181-edeb1100-bd7c-11e8-8aa0-63b68b74038f.JPG)
![img_0839](https://user-images.githubusercontent.com/925500/45865182-ee83a780-bd7c-11e8-943d-1b7e7170a5f2.JPG)

**Comment by moolen** [comment]
Thank you @mibcadet! I'm testing it w/ bspwm and a external screen.
I managed to reproduce the issue and found a workaround for now. Your setup is as follows based on the information from above:

```
         +----------------------------------------+
         |             |             |            |
         |    DP1      |   DP2-2     |    eDP1    |
         |             |             |  (primary) |
         +----------------------------------------+
```
With the point 0-0 at the bottom left of DP1 and 5760x1080 at the top right of eDP1.
However, the screenshot library recognizes the monitors at `X:-3840, Y:-384` and `X:-1920, Y:-384`. I use those coordinates to position the overlay windows. 

With a little bit of trial and error i found out, that those coordinates are relative to the `primary` screen. I'm not sure what the cause for that is; the lib uses `xinerama` which is obsolete as far as i can tell.
Now, when i set the most left window as the primary, the coordinates are all positive and the windows are then properly positioned.

```bash
$ xrandr --output DP-1 --mode 1920x1200 --primary --left-of DP2-2
```

I'll get back to you once i have a proper fix for that.

**Comment by mibcadet** [comment]
Ok I understand, so it is no problem for me to set most left as a primary. 

However, It will be good point for you to handle my current setup too :)

Thank you for all job you've done here!

**Comment by mibcadet** [comment]
I can confirm latest releases works perferct both with primary most left and right screen, I think this issue is solved (at least on my setup).

**Comment by moolen** [comment]
I'll close this then, thank you!
