### ISSUE TITLE
Floating window stays visible on non focused head in multi-head

### ISSUE THREAD

**Issue by mibcadet** [moolen/glitchlock#2]
Hi,

in BSPWM when you have floating window on one monitor, and you got focus on different monitor while running glitchlock then floating window stays visible on top of glitchlock.

Screenshot:
![2018-09-24-105853_1346x586_scrot](https://user-images.githubusercontent.com/925500/45944124-50e0e000-bfe9-11e8-9688-c6795b45ac39.png)

You got my configuration in issue #1, still the same. I've used latest release.

 Workaround - set focus on monitor (for example by moving mouse to this monitor) with floating window when running glitchlock.

**Comment by moolen** [comment]
I saw this behavior previously with notifications (e.g. google chrome), too. I can clearly reproduce the issue, i'll have a look. Thank you!

**edit** seems like there is a `xcb` api that [i3lock](https://github.com/i3/i3lock/blob/ad680b40192f665dd7af4d62ab6996318e275cb6/xcb.c#L156) uses to put the overlay window on top of all other windows.

**Comment by moolen** [comment]
I just released [0.3](https://github.com/moolen/glitchlock/releases/tag/0.3) which fixes this issue (and probably #3 too). I tested it using your description above. It would be great if you could test this, too and give me feedback :heart:

**Comment by mibcadet** [comment]
Seems to be fixed issue so feel free to close it.
Just one new thing appeared, after this fix - mouse pointer stays visible on top of glitchlock, but this is minor thing.
