### ISSUE TITLE
Doesn't go fullscreen under Herbstluftwm.

### ISSUE THREAD

**Issue by vifino** [moolen/glitchlock#3]
Weirdly enough, glitchlock seems to not go fullscreen, instead tiling like the other windows, yet locking input like it should.

Is there a specific behaviour which glitchlock doesn't do that slock, i3lock and friends do?

I'd love to use it on my musl void linux install. :)

PS: I had gotten it to work on OpenBSD too, I might dig out the changes. Same behaviour as this, though.

**Comment by moolen** [comment]
Most window manager support ["Extended Window Manager Hints"](https://standards.freedesktop.org/wm-spec/wm-spec-latest.html), specificially `_NET_WM_STATE_FULLSCREEN` should do the trick to set a window fullscreen; however not all WM necessarily obey those hints.

I'll take a look and make it work with Herbstluftwm.

I'd love to support BSD based systems, feel free to contribute!

**Comment by vifino** [comment]
I am wondering why i3lock and friends work with the same configuration, though...

LMK if you want me to test something. :)

**Comment by moolen** [comment]
I just pushed [0.3](https://github.com/moolen/glitchlock/releases/tag/0.3) which includes a fix for setting the window to fullscreen mode. It would be great if you could test it :heart:

**Comment by vifino** [comment]
Works now! Thank you!

Is there supposed to be a password typing indicator of some sort?
I haven't seen anything like that, but I like the locker!

I've been working on a farbfeld glitching filter, which I use similar to xero's glitchlock,
not sure which glitching I like more, though.

If you wanna check it out, it's here: https://github.com/vifino/ff-glitch

**Comment by moolen** [comment]
I implemented xero's jpg-crunching-based glitch, however that's "problematic" for the golang image decoder - it errors out while trying to decode it.

> Is there supposed to be a password typing indicator of some sort?

I played around with that, but i did not come up with something i *really* like.

Thank you for your feedback, much appreciated!
