### ISSUE TITLE
BSPWM Fullscreen app overlays glitchlock

### ISSUE THREAD

**Issue by mibcadet** [moolen/glitchlock#4]
Hi, gotta found one issue more.

I got my multihead setup like on issue #1.

While I go fullscreen with some window on one monitor, then I focus another monitor, launch glitchlock, then that fullscreen window stays visible after glitchlock started. This window is not usable but still visible.

**Comment by mibcadet** [comment]
Thanks for update!

Your commit e7c236a fixes this issue, feel free to close it.

**Comment by moolen** [comment]
:+1: thanks for your feedback!
