### ISSUE TITLE
development headers 

### ISSUE THREAD

**Issue by dystopianmonarchy** [moolen/glitchlock#5]
How do I install the development headers for pam?

**Comment by moolen** [comment]
For archlinux you can install the `pam` package it contains the [necessary files](https://www.archlinux.org/packages/core/x86_64/pam) `pam-devel` for CentOS/RHEL or `libpam0g-dev` for [debian/ubuntu](https://packages.debian.org/stretch/libpam0g-dev).

**Comment by moolen** [comment]
I've added the requirements to the `README`. Thank you for rising this issue <3
