### ISSUE TITLE
input not work with kernel 4.20

### ISSUE THREAD

**Issue by mibcadet** [moolen/glitchlock#7]
Hello!

I've found an issue with glitchlock on ArchLinux.

Archlinux details:
Linux mDev 4.20.10-arch1-1-ARCH #1 SMP PREEMPT Fri Feb 15 17:49:06 UTC 2019 x86_64 GNU/Linux

binary version: glitchlock 0.33-1

Issue decription:
After locking screen keyboard input is not working (like not a single letter is typed in).
I saw same problem with other screenlocks like slimlock, but today I did pacman -Syu update and slimlock already works again.

I am not sure if this is glitchlock issue, but it seems like glitchlock needs some update for latest linux related updates.

I've not found any issues in journalctl while trying to unlock, neither in dmesg.

Please let me know what else I could post if something more is needed.

**Comment by moolen** [comment]
This was adressed in #8. Feel free to reopen if you have any issues.
